### ISSUE TITLE
Slower than LynxChan and crashes

### ISSUE THREAD

**Issue by ghost** [Circlepuller/Tinyboard#6]
Your fork is WAY slower than LYNXCHAN and constantly crashes. You have been working on it for over 2 years and it actually gets more and more buggy. Maybe hire someone who knows how to code to fix it?

**Comment by PVNFU-28** [comment]
> Your fork is WAY slower than LYNXCHAN

[citation needed]

**Comment by Circlepuller** [comment]
I have no idea what bugs you're talking about? I'll agree with @panfu28 here that your claims are sort of baseless. If you disagree with this, feel free to describe the bug you're talking about, or if speed is a concern, benchmark data.

As for hiring someone, Tinyboard is community managed. I am not paid to write this software by any company, and the only source of income I can make off of it is a Patreon that I have set up. 

I hope this clears up any confusion.
